method: org.apache.fop.util.LogUtil.handleException:1019614530
568662539:log := @parameter0: org.apache.commons.logging.Log
1209063823:e := @parameter1: java.lang.Exception
1245405247:strict := @parameter2: boolean
1143048906:if strict == 0 goto $r1 = virtualinvoke e.<java.lang.Exception: java.lang.String getMessage()>()
1792517366:$z0 = e instanceof org.apache.fop.apps.FOPException
1938770246:if $z0 == 0 goto $r0 = new org.apache.fop.apps.FOPException
1882532051:$r0 = (org.apache.fop.apps.FOPException) e
839609906:throw $r0
208645705:$r0 = new org.apache.fop.apps.FOPException
324559630:specialinvoke $r0.<org.apache.fop.apps.FOPException: void <init>(java.lang.Exception)>(e)
265238030:throw $r0
250237441:$r1 = virtualinvoke e.<java.lang.Exception: java.lang.String getMessage()>()
967690061:interfaceinvoke log.<org.apache.commons.logging.Log: void error(java.lang.Object)>($r1)
1073196496:return
