method: org.apache.fop.apps.FOURIResolver.handleException:72731063
1204880262:this := @this: org.apache.fop.apps.FOURIResolver
1799255871:e := @parameter0: java.lang.Exception
1376190490:errorStr := @parameter1: java.lang.String
1234687240:strict := @parameter2: boolean
1284604644:if strict == 0 goto $r1 = this.<org.apache.fop.apps.FOURIResolver: org.apache.commons.logging.Log log>
1697148417:$r0 = new javax.xml.transform.TransformerException
753172171:specialinvoke $r0.<javax.xml.transform.TransformerException: void <init>(java.lang.String,java.lang.Throwable)>(errorStr, e)
1296062579:throw $r0
2011736183:$r1 = this.<org.apache.fop.apps.FOURIResolver: org.apache.commons.logging.Log log>
1802588998:$r2 = virtualinvoke e.<java.lang.Exception: java.lang.String getMessage()>()
1561481157:interfaceinvoke $r1.<org.apache.commons.logging.Log: void error(java.lang.Object)>($r2)
1563639359:return
