method: org.apache.fop.apps.FOPException.printStackTrace:378075614
2087237916:this := @this: org.apache.fop.apps.FOPException
1062280467:writer := @parameter0: java.io.PrintWriter
1136073313:l2 = writer
707066114:entermonitor writer
1894424376:specialinvoke this.<org.xml.sax.SAXException: void printStackTrace(java.io.PrintWriter)>(writer)
480044000:$r1 = virtualinvoke this.<org.apache.fop.apps.FOPException: java.lang.Exception getException()>()
3446221:if $r1 == null goto $r2 = virtualinvoke this.<org.apache.fop.apps.FOPException: java.lang.Throwable getRootException()>()
1995141779:virtualinvoke writer.<java.io.PrintWriter: void println(java.lang.String)>("\n---------\n")
1378001179:$r1 = virtualinvoke this.<org.apache.fop.apps.FOPException: java.lang.Exception getException()>()
309957702:virtualinvoke $r1.<java.lang.Exception: void printStackTrace(java.io.PrintWriter)>(writer)
1157533748:$r2 = virtualinvoke this.<org.apache.fop.apps.FOPException: java.lang.Throwable getRootException()>()
615344463:if $r2 == null goto exitmonitor l2
485427302:virtualinvoke writer.<java.io.PrintWriter: void println(java.lang.String)>("\n---------\n")
1308643847:$r2 = virtualinvoke this.<org.apache.fop.apps.FOPException: java.lang.Throwable getRootException()>()
218064204:virtualinvoke $r2.<java.lang.Throwable: void printStackTrace(java.io.PrintWriter)>(writer)
144654895:exitmonitor l2
263331861:goto [?= return]
725401522:$r3 := @caughtexception
2002275007:l3 = $r3
1449814968:exitmonitor l2
231016294:throw l3
40419482:return
