method: org.apache.fop.apps.FopFactory.resolveURI:280364760
2100391424:this := @this: org.apache.fop.apps.FopFactory
942473782:href := @parameter0: java.lang.String
317473802:baseUri := @parameter1: java.lang.String
1521452451:source = null
364082269:$r0 = this.<org.apache.fop.apps.FopFactory: org.apache.fop.apps.FOURIResolver foURIResolver>
1520072142:source = virtualinvoke $r0.<org.apache.fop.apps.FOURIResolver: javax.xml.transform.Source resolve(java.lang.String,java.lang.String)>(href, baseUri)
1387025882:goto [?= return source]
866496212:$r1 := @caughtexception
809010589:e = $r1
1322000166:$r2 = <org.apache.fop.apps.FopFactory: org.apache.commons.logging.Log log>
990978100:$r3 = new java.lang.StringBuffer
799545551:specialinvoke $r3.<java.lang.StringBuffer: void <init>()>()
640485108:$r3 = virtualinvoke $r3.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>("Attempt to resolve URI \'")
955537774:$r3 = virtualinvoke $r3.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>(href)
599587451:$r3 = virtualinvoke $r3.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>("\' failed: ")
1273017233:$r4 = virtualinvoke $r3.<java.lang.StringBuffer: java.lang.String toString()>()
208206480:interfaceinvoke $r2.<org.apache.commons.logging.Log: void error(java.lang.Object,java.lang.Throwable)>($r4, e)
1838835227:return source
