method: org.apache.fop.render.afp.exceptions.NestedRuntimeException.getMessage:814691969
606182573:this := @this: org.apache.fop.render.afp.exceptions.NestedRuntimeException
1854037319:$r0 = this.<org.apache.fop.render.afp.exceptions.NestedRuntimeException: java.lang.Throwable underlyingException>
817502463:if $r0 != null goto $r2 = new java.lang.StringBuffer
1684938432:$r1 = specialinvoke this.<java.lang.RuntimeException: java.lang.String getMessage()>()
2040857282:return $r1
1079528690:$r2 = new java.lang.StringBuffer
257031858:specialinvoke $r2.<java.lang.StringBuffer: void <init>()>()
179633548:$r3 = specialinvoke this.<java.lang.RuntimeException: java.lang.String getMessage()>()
1886517201:$r2 = virtualinvoke $r2.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>($r3)
1961891596:$r2 = virtualinvoke $r2.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>("; nested exception is ")
245900397:$r4 = this.<org.apache.fop.render.afp.exceptions.NestedRuntimeException: java.lang.Throwable underlyingException>
1089435551:$r5 = virtualinvoke $r4.<java.lang.Object: java.lang.Class getClass()>()
697731335:$r3 = virtualinvoke $r5.<java.lang.Class: java.lang.String getName()>()
1509834725:$r2 = virtualinvoke $r2.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>($r3)
1125450123:$r1 = virtualinvoke $r2.<java.lang.StringBuffer: java.lang.String toString()>()
404254485:return $r1
